/**
 * Gallery Data - FASE 25: Hub de Inspección Patrimonial ENKA
 * 53 fotografías distribuidas en 4 Ejes Probatorios (ciclo rotativo)
 * Thumbnails: usar versión optimizada (ej. Cloudflare Images / imgix / Drive thumbnail)
 * Full: URL original en Drive (requiere auth para privados)
 */

export const galleryData = [
   // Eje I: Contexto y Fachada (13 imágenes)
   {
      idx: 1,
      name: "WhatsApp Image 2026-07-25 at 8.41.10 AM.jpeg",
      eje: 1,
      ejeClass: "eje-1",
      ejeLabel: "Eje I: Contexto y Fachada",
      thumb: "https://drive.google.com/drive/folders/1oq-3k-wP2NEOUZrRoPTJXtxlBwbWc0OY?usp=drive_link",
      full: "https://drive.google.com/drive/folders/1oq-3k-wP2NEOUZrRoPTJXtxlBwbWc0OY?usp=drive_link",
      alt: "Inspección ENKA #1",
   },
   {
      idx: 5,
      name: "WhatsApp Image 2026-07-27 at 2.08.16 PM.jpeg",
      eje: 1,
      ejeClass: "eje-1",
      ejeLabel: "Eje I: Contexto y Fachada",
      thumb: "https://drive.google.com/drive/folders/1oq-3k-wP2NEOUZrRoPTJXtxlBwbWc0OY?usp=drive_link",
      full: "https://drive.google.com/drive/folders/1oq-3k-wP2NEOUZrRoPTJXtxlBwbWc0OY?usp=drive_link",
      alt: "Inspección ENKA #5",
   },
   {
      idx: 9,
      name: "WhatsApp Image 2026-07-27 at 2.08.18 PM (2).jpeg",
      eje: 1,
      ejeClass: "eje-1",
      ejeLabel: "Eje I: Contexto y Fachada",
      thumb: "https://drive.google.com/drive/folders/1oq-3k-wP2NEOUZrRoPTJXtxlBwbWc0OY?usp=drive_link",
      full: "https://drive.google.com/drive/folders/1oq-3k-wP2NEOUZrRoPTJXtxlBwbWc0OY?usp=drive_link",
      eje: 1,
      alt: "Inspección ENKA #9",
   },
   {
      idx: 13,
      name: "WhatsApp Image 2026-07-27 at 2.08.19 PM.jpeg",
      eje: 1,
      ejeClass: "eje-1",
      ejeLabel: "Eje I: Contexto y Fachada",
      thumb: "https://drive.google.com/drive/folders/1oq-3k-wP2NEOUZrRoPTJXtxlBwbWc0OY?usp=drive_link",
      full: "https://drive.google.com/drive/folders/1oq-3k-wP2NEOUZrRoPTJXtxlBwbWc0OY?usp=drive_link",
      alt: "Inspección ENKA #13",
   },
   {
      idx: 17,
      name: "WhatsApp Image 2026-07-28 at 12.27.08 PM.jpeg",
      eje: 1,
      ejeClass: "eje-1",
      ejeLabel: "Eje I: Contexto y Fachada",
      thumb: "https://drive.google.com/drive/folders/1oq-3k-wP2NEOUZrRoPTJXtxlBwbWc0OY?usp=drive_link",
      full: "https://drive.google.com/drive/folders/1oq-3k-wP2NEOUZrRoPTJXtxlBwbWc0OY?usp=drive_link",
      alt: "Inspección ENKA #17",
   },
   {
      idx: 21,
      name: "WhatsApp Image 2026-07-28 at 5.30.19 PM (1).jpeg",
      eje: 1,
      ejeClass: "eje-1",
      ejeLabel: "Eje I: Contexto y Fachada",
      thumb: "https://drive.google.com/drive/folders/1oq-3k-wP2NEOUZrRoPTJXtxlBwbWc0OY?usp=drive_link",
      full: "https://drive.google.com/drive/folders/1oq-3k-wP2NEOUZrRoPTJXtxlBwbWc0OY?usp=drive_link",
      alt: "Inspección ENKA #21",
   },
   {
      idx: 25,
      name: "WhatsApp Image 2026-07-28 at 5.30.20 PM (1).jpeg",
      eje: 1,
      ejeClass: "eje-1",
      ejeLabel: "Eje I: Contexto y Fachada",
      thumb: "https://drive.google.com/drive/folders/1oq-3k-wP2NEOUZrRoPTJXtxlBwbWc0OY?usp=drive_link",
      full: "https://drive.google.com/drive/folders/1oq-3k-wP2NEOUZrRoPTJXtxlBwbWc0OY?usp=drive_link",
      alt: "Inspección ENKA #25",
   },
   {
      idx: 29,
      name: "WhatsApp Image 2026-07-28 at 7.06.42 PM.jpeg",
      eje: 1,
      ejeClass: "eje-1",
      ejeLabel: "Eje I: Contexto y Fachada",
      thumb: "https://drive.google.com/drive/folders/1oq-3k-wP2NEOUZrRoPTJXtxlBwbWc0OY?usp=drive_link",
      full: "https://drive.google.com/drive/folders/1oq-3k-wP2NEOUZrRoPTJXtxlBwbWc0OY?usp=drive_link",
      alt: "Inspección ENKA #29",
   },
   {
      idx: 33,
      name: "WhatsApp Image 2026-07-31 at 5.41.59 PM.jpeg",
      eje: 1,
      ejeClass: "eje-1",
      ejeLabel: "Eje I: Contexto y Fachada",
      thumb: "https://drive.google.com/drive/folders/1oq-3k-wP2NEOUZrRoPTJXtxlBwbWc0OY?usp=drive_link",
      full: "https://drive.google.com/drive/folders/1oq-3k-wP2NEOUZrRoPTJXtxlBwbWc0OY?usp=drive_link",
      alt: "Inspección ENKA #33",
   },
   {
      idx: 37,
      name: "WhatsApp Image 2026-07-31 at 9.22.12 AM.jpeg",
      eje: 1,
      ejeClass: "eje-1",
      ejeLabel: "Eje I: Contexto y Fachada",
      thumb: "https://drive.google.com/drive/folders/1oq-3k-wP2NEOUZrRoPTJXtxlBwbWc0OY?usp=drive_link",
      full: "https://drive.google.com/drive/folders/1oq-3k-wP2NEOUZrRoPTJXtxlBwbWc0OY?usp=drive_link",
      alt: "Inspección ENKA #37",
   },
   {
      idx: 41,
      name: "WhatsApp Image 2026-08-01 at 1.11.31 PM (2).jpeg",
      eje: 1,
      ejeClass: "eje-1",
      ejeLabel: "Eje I: Contexto y Fachada",
      thumb: "https://drive.google.com/drive/folders/1oq-3k-wP2NEOUZrRoPTJXtxlBwbWc0OY?usp=drive_link",
      full: "https://drive.google.com/drive/folders/1oq-3k-wP2NEOUZrRoPTJXtxlBwbWc0OY?usp=drive_link",
      alt: "Inspección ENKA #41",
   },
   {
      idx: 45,
      name: "WhatsApp Image 2026-08-01 at 1.11.33 PM (2).jpeg",
      eje: 1,
      ejeClass: "eje-1",
      ejeLabel: "Eje I: Contexto y Fachada",
      thumb: "https://drive.google.com/drive/folders/1oq-3k-wP2NEOUZrRoPTJXtxlBwbWc0OY?usp=drive_link",
      full: "https://drive.google.com/drive/folders/1oq-3k-wP2NEOUZrRoPTJXtxlBwbWc0OY?usp=drive_link",
      alt: "Inspección ENKA #45",
   },
   {
      idx: 49,
      name: "WhatsApp Image 2026-08-03 at 11.16.16 AM.jpeg",
      eje: 1,
      ejeClass: "eje-1",
      ejeLabel: "Eje I: Contexto y Fachada",
      thumb: "https://drive.google.com/drive/folders/1oq-3k-wP2NEOUZrRoPTJXtxlBwbWc0OY?usp=drive_link",
      full: "https://drive.google.com/drive/folders/1oq-3k-wP2NEOUZrRoPTJXtxlBwbWc0OY?usp=drive_link",
      alt: "Inspección ENKA #49",
   },
   {
      idx: 53,
      name: "WhatsApp Image 2026-08-03 at 9.14.41 AM.jpeg",
      eje: 1,
      ejeClass: "eje-1",
      ejeLabel: "Eje I: Contexto y Fachada",
      thumb: "https://drive.google.com/drive/folders/1oq-3k-wP2NEOUZrRoPTJXtxlBwbWc0OY?usp=drive_link",
      full: "https://drive.google.com/drive/folders/1oq-3k-wP2NEOUZrRoPTJXtxlBwbWc0OY?usp=drive_link",
      alt: "Inspección ENKA #53",
   },

   // Eje II: Autogestión Azotea (13 imágenes)
   {
      idx: 2,
      name: "WhatsApp Image 2026-07-25 at 8.42.59 AM.jpeg",
      eje: 2,
      ejeClass: "eje-2",
      ejeLabel: "Eje II: Autogestión Azotea",
      thumb: "https://drive.google.com/drive/folders/1oq-3k-wP2NEOUZrRoPTJXtxlBwbWc0OY?usp=drive_link",
      full: "https://drive.google.com/drive/folders/1oq-3k-wP2NEOUZrRoPTJXtxlBwbWc0OY?usp=drive_link",
      alt: "Inspección ENKA #2",
   },
   {
      idx: 6,
      name: "WhatsApp Image 2026-07-27 at 2.08.17 PM (1).jpeg",
      eje: 2,
      ejeClass: "eje-2",
      ejeLabel: "Eje II: Autogestión Azotea",
      thumb: "https://drive.google.com/drive/folders/1oq-3k-wP2NEOUZrRoPTJXtxlBwbWc0OY?usp=drive_link",
      full: "https://drive.google.com/drive/folders/1oq-3k-wP2NEOUZrRoPTJXtxlBwbWc0OY?usp=drive_link",
      eje: 2,
      alt: "Inspección ENKA #6",
   },
   {
      idx: 10,
      name: "WhatsApp Image 2026-07-27 at 2.08.18 PM (3).jpeg",
      eje: 2,
      ejeClass: "eje-2",
      ejeLabel: "Eje II: Autogestión Azotea",
      thumb: "https://drive.google.com/drive/folders/1oq-3k-wP2NEOUZrRoPTJXtxlBwbWc0OY?usp=drive_link",
      full: "https://drive.google.com/drive/folders/1oq-3k-wP2NEOUZrRoPTJXtxlBwbWc0OY?usp=drive_link",
      eje: 2,
      alt: "Inspección ENKA #10",
   },
   {
      idx: 14,
      name: "WhatsApp Image 2026-07-28 at 11.48.52 AM.jpeg",
      eje: 2,
      ejeClass: "eje-2",
      ejeLabel: "Eje II: Autogestión Azotea",
      thumb: "https://drive.google.com/drive/folders/1oq-3k-wP2NEOUZrRoPTJXtxlBwbWc0OY?usp=drive_link",
      full: "https://drive.google.com/drive/folders/1oq-3k-wP2NEOUZrRoPTJXtxlBwbWc0OY?usp=drive_link",
      alt: "Inspección ENKA #14",
   },
   {
      idx: 18,
      name: "WhatsApp Image 2026-07-28 at 2.35.44 PM.jpeg",
      eje: 2,
      ejeClass: "eje-2",
      ejeLabel: "Eje II: Autogestión Azotea",
      thumb: "https://drive.google.com/drive/folders/1oq-3k-wP2NEOUZrRoPTJXtxlBwbWc0OY?usp=drive_link",
      full: "https://drive.google.com/drive/folders/1oq-3k-wP2NEOUZrRoPTJXtxlBwbWc0OY?usp=drive_link",
      alt: "Inspección ENKA #18",
   },
   {
      idx: 22,
      name: "WhatsApp Image 2026-07-28 at 5.30.19 PM (2).jpeg",
      eje: 2,
      ejeClass: "eje-2",
      ejeLabel: "Eje II: Autogestión Azotea",
      thumb: "https://drive.google.com/drive/folders/1oq-3k-wP2NEOUZrRoPTJXtxlBwbWc0OY?usp=drive_link",
      full: "https://drive.google.com/drive/folders/1oq-3k-wP2NEOUZrRoPTJXtxlBwbWc0OY?usp=drive_link",
      alt: "Inspección ENKA #22",
   },
   {
      idx: 26,
      name: "WhatsApp Image 2026-07-28 at 5.30.20 PM (2).jpeg",
      eje: 2,
      ejeClass: "eje-2",
      ejeLabel: "Eje II: Autogestión Azotea",
      thumb: "https://drive.google.com/drive/folders/1oq-3k-wP2NEOUZrRoPTJXtxlBwbWc0OY?usp=drive_link",
      full: "https://drive.google.com/drive/folders/1oq-3k-wP2NEOUZrRoPTJXtxlBwbWc0OY?usp=drive_link",
      alt: "Inspección ENKA #26",
   },
   {
      idx: 30,
      name: "WhatsApp Image 2026-07-28 at 7.06.55 PM.jpeg",
      eje: 2,
      ejeClass: "eje-2",
      ejeLabel: "Eje II: Autogestión Azotea",
      thumb: "https://drive.google.com/drive/folders/1oq-3k-wP2NEOUZrRoPTJXtxlBwbWc0OY?usp=drive_link",
      full: "https://drive.google.com/drive/folders/1oq-3k-wP2NEOUZrRoPTJXtxlBwbWc0OY?usp=drive_link",
      alt: "Inspección ENKA #30",
   },
   {
      idx: 34,
      name: "WhatsApp Image 2026-07-31 at 5.42.39 PM.jpeg",
      eje: 2,
      ejeClass: "eje-2",
      ejeLabel: "Eje II: Autogestión Azotea",
      thumb: "https://drive.google.com/drive/folders/1oq-3k-wP2NEOUZrRoPTJXtxlBwbWc0OY?usp=drive_link",
      full: "https://drive.google.com/drive/folders/1oq-3k-wP2NEOUZrRoPTJXtxlBwbWc0OY?usp=drive_link",
      alt: "Inspección ENKA #34",
   },
   {
      idx: 38,
      name: "WhatsApp Image 2026-07-31 at 9.26.31 AM.jpeg",
      eje: 2,
      ejeClass: "eje-2",
      ejeLabel: "Eje II: Autogestión Azotea",
      thumb: "https://drive.google.com/drive/folders/1oq-3k-wP2NEOUZrRoPTJXtxlBwbWc0OY?usp=drive_link",
      full: "https://drive.google.com/drive/folders/1oq-3k-wP2NEOUZrRoPTJXtxlBwbWc0OY?usp=drive_link",
      alt: "Inspección ENKA #38",
   },
   {
      idx: 42,
      name: "WhatsApp Image 2026-08-01 at 1.11.31 PM.jpeg",
      eje: 2,
      ejeClass: "eje-2",
      ejeLabel: "Eje II: Autogestión Azotea",
      thumb: "https://drive.google.com/drive/folders/1oq-3k-wP2NEOUZrRoPTJXtxlBwbWc0OY?usp=drive_link",
      full: "https://drive.google.com/drive/folders/1oq-3k-wP2NEOUZrRoPTJXtxlBwbWc0OY?usp=drive_link",
      alt: "Inspección ENKA #42",
   },
   {
      idx: 46,
      name: "WhatsApp Image 2026-08-01 at 1.11.33 PM.jpeg",
      eje: 2,
      ejeClass: "eje-2",
      ejeLabel: "Eje II: Autogestión Azotea",
      thumb: "https://drive.google.com/drive/folders/1oq-3k-wP2NEOUZrRoPTJXtxlBwbWc0OY?usp=drive_link",
      full: "https://drive.google.com/drive/folders/1oq-3k-wP2NEOUZrRoPTJXtxlBwbWc0OY?usp=drive_link",
      alt: "Inspección ENKA #46",
   },
   {
      idx: 50,
      name: "WhatsApp Image 2026-08-03 at 11.20.14 AM.jpeg",
      eje: 2,
      ejeClass: "eje-2",
      ejeLabel: "Eje II: Autogestión Azotea",
      thumb: "https://drive.google.com/drive/folders/1oq-3k-wP2NEOUZrRoPTJXtxlBwbWc0OY?usp=drive_link",
      full: "https://drive.google.com/drive/folders/1oq-3k-wP2NEOUZrRoPTJXtxlBwbWc0OY?usp=drive_link",
      alt: "Inspección ENKA #50",
   },

   // Eje III: Patologías Estructurales (14 imágenes)
   {
      idx: 3,
      name: "WhatsApp Image 2026-07-25 at 8.44.19 AM.jpeg",
      eje: 3,
      ejeClass: "eje-3",
      ejeLabel: "Eje III: Patologías Estructurales",
      thumb: "https://drive.google.com/drive/folders/1oq-3k-wP2NEOUZrRoPTJXtxlBwbWc0OY?usp=drive_link",
      full: "https://drive.google.com/drive/folders/1oq-3k-wP2NEOUZrRoPTJXtxlBwbWc0OY?usp=drive_link",
      alt: "Inspección ENKA #3",
   },
   {
      idx: 7,
      name: "WhatsApp Image 2026-07-27 at 2.08.17 PM.jpeg",
      eje: 3,
      ejeClass: "eje-3",
      ejeLabel: "Eje III: Patologías Estructurales",
      thumb: "https://drive.google.com/drive/folders/1oq-3k-wP2NEOUZrRoPTJXtxlBwbWc0OY?usp=drive_link",
      full: "https://drive.google.com/drive/folders/1oq-3k-wP2NEOUZrRoPTJXtxlBwbWc0OY?usp=drive_link",
      alt: "Inspección ENKA #7",
   },
   {
      idx: 11,
      name: "WhatsApp Image 2026-07-27 at 2.08.18 PM (4).jpeg",
      eje: 3,
      ejeClass: "eje-3",
      ejeLabel: "Eje III: Patologías Estructurales",
      thumb: "https://drive.google.com/drive/folders/1oq-3k-wP2NEOUZrRoPTJXtxlBwbWc0OY?usp=drive_link",
      full: "https://drive.google.com/drive/folders/1oq-3k-wP2NEOUZrRoPTJXtxlBwbWc0OY?usp=drive_link",
      eje: 3,
      alt: "Inspección ENKA #11",
   },
   {
      idx: 15,
      name: "WhatsApp Image 2026-07-28 at 11.48.59 AM.jpeg",
      eje: 3,
      ejeClass: "eje-3",
      ejeLabel: "Eje III: Patologías Estructurales",
      thumb: "https://drive.google.com/drive/folders/1oq-3k-wP2NEOUZrRoPTJXtxlBwbWc0OY?usp=drive_link",
      full: "https://drive.google.com/drive/folders/1oq-3k-wP2NEOUZrRoPTJXtxlBwbWc0OY?usp=drive_link",
      alt: "Inspección ENKA #15",
   },
   {
      idx: 19,
      name: "WhatsApp Image 2026-07-28 at 2.42.47 PM.jpeg",
      eje: 3,
      ejeClass: "eje-3",
      ejeLabel: "Eje III: Patologías Estructurales",
      thumb: "https://drive.google.com/drive/folders/1oq-3k-wP2NEOUZrRoPTJXtxlBwbWc0OY?usp=drive_link",
      full: "https://drive.google.com/drive/folders/1oq-3k-wP2NEOUZrRoPTJXtxlBwbWc0OY?usp=drive_link",
      alt: "Inspección ENKA #19",
   },
   {
      idx: 23,
      name: "WhatsApp Image 2026-07-28 at 5.30.19 PM (3).jpeg",
      eje: 3,
      ejeClass: "eje-3",
      ejeLabel: "Eje III: Patologías Estructurales",
      thumb: "https://drive.google.com/drive/folders/1oq-3k-wP2NEOUZrRoPTJXtxlBwbWc0OY?usp=drive_link",
      full: "https://drive.google.com/drive/folders/1oq-3k-wP2NEOUZrRoPTJXtxlBwbWc0OY?usp=drive_link",
      alt: "Inspección ENKA #23",
   },
   {
      idx: 27,
      name: "WhatsApp Image 2026-07-28 at 5.30.20 PM.jpeg",
      eje: 3,
      ejeClass: "eje-3",
      ejeLabel: "Eje III: Patologías Estructurales",
      thumb: "https://drive.google.com/drive/folders/1oq-3k-wP2NEOUZrRoPTJXtxlBwbWc0OY?usp=drive_link",
      full: "https://drive.google.com/drive/folders/1oq-3k-wP2NEOUZrRoPTJXtxlBwbWc0OY?usp=drive_link",
      alt: "Inspección ENKA #27",
   },
   {
      idx: 31,
      name: "WhatsApp Image 2026-07-30 at 11.50.40 AM.jpeg",
      eje: 3,
      ejeClass: "eje-3",
      ejeLabel: "Eje III: Patologías Estructurales",
      thumb: "https://drive.google.com/drive/folders/1oq-3k-wP2NEOUZrRoPTJXtxlBwbWc0OY?usp=drive_link",
      full: "https://drive.google.com/drive/folders/1oq-3k-wP2NEOUZrRoPTJXtxlBwbWc0OY?usp=drive_link",
      alt: "Inspección ENKA #31",
   },
   {
      idx: 35,
      name: "WhatsApp Image 2026-07-31 at 8.42.43 AM.jpeg",
      eje: 3,
      ejeClass: "eje-3",
      ejeLabel: "Eje III: Patologías Estructurales",
      thumb: "https://drive.google.com/drive/folders/1oq-3k-wP2NEOUZrRoPTJXtxlBwbWc0OY?usp=drive_link",
      full: "https://drive.google.com/drive/folders/1oq-3k-wP2NEOUZrRoPTJXtxlBwbWc0OY?usp=drive_link",
      alt: "Inspección ENKA #35",
   },
   {
      idx: 39,
      name: "WhatsApp Image 2026-08-01 at 1.11.30 PM.jpeg",
      eje: 3,
      ejeClass: "eje-3",
      ejeLabel: "Eje III: Patologías Estructurales",
      thumb: "https://drive.google.com/drive/folders/1oq-3k-wP2NEOUZrRoPTJXtxlBwbWc0OY?usp=drive_link",
      full: "https://drive.google.com/drive/folders/1oq-3k-wP2NEOUZrRoPTJXtxlBwbWc0OY?usp=drive_link",
      alt: "Inspección ENKA #39",
   },
   {
      idx: 43,
      name: "WhatsApp Image 2026-08-01 at 1.11.32 PM.jpeg",
      eje: 3,
      ejeClass: "eje-3",
      ejeLabel: "Eje III: Patologías Estructurales",
      thumb: "https://drive.google.com/drive/folders/1oq-3k-wP2NEOUZrRoPTJXtxlBwbWc0OY?usp=drive_link",
      full: "https://drive.google.com/drive/folders/1oq-3k-wP2NEOUZrRoPTJXtxlBwbWc0OY?usp=drive_link",
      alt: "Inspección ENKA #43",
   },
   {
      idx: 47,
      name: "WhatsApp Image 2026-08-01 at 1.11.43 PM.jpeg",
      eje: 3,
      ejeClass: "eje-3",
      ejeLabel: "Eje III: Patologías Estructurales",
      thumb: "https://drive.google.com/drive/folders/1oq-3k-wP2NEOUZrRoPTJXtxlBwbWc0OY?usp=drive_link",
      full: "https://drive.google.com/drive/folders/1oq-3k-wP2NEOUZrRoPTJXtxlBwbWc0OY?usp=drive_link",
      alt: "Inspección ENKA #47",
   },
   {
      idx: 51,
      name: "WhatsApp Image 2026-08-03 at 11.21.02 AM.jpeg",
      eje: 3,
      ejeClass: "eje-3",
      ejeLabel: "Eje III: Patologías Estructurales",
      thumb: "https://drive.google.com/drive/folders/1oq-3k-wP2NEOUZrRoPTJXtxlBwbWc0OY?usp=drive_link",
      full: "https://drive.google.com/drive/folders/1oq-3k-wP2NEOUZrRoPTJXtxlBwbWc0OY?usp=drive_link",
      alt: "Inspección ENKA #51",
   },

   // Eje IV: Evaluación de Riesgo Civil (13 imágenes)
   {
      idx: 4,
      name: "WhatsApp Image 2026-07-27 at 10.40.49 AM.jpeg",
      eje: 4,
      ejeClass: "eje-4",
      ejeLabel: "Eje IV: Evaluación de Riesgo Civil",
      thumb: "https://drive.google.com/drive/folders/1oq-3k-wP2NEOUZrRoPTJXtxlBwbWc0OY?usp=drive_link",
      full: "https://drive.google.com/drive/folders/1oq-3k-wP2NEOUZrRoPTJXtxlBwbWc0OY?usp=drive_link",
      alt: "Inspección ENKA #4",
   },
   {
      idx: 8,
      name: "WhatsApp Image 2026-07-27 at 2.08.18 PM (1).jpeg",
      eje: 4,
      ejeClass: "eje-4",
      ejeLabel: "Eje IV: Evaluación de Riesgo Civil",
      thumb: "https://drive.google.com/drive/folders/1oq-3k-wP2NEOUZrRoPTJXtxlBwbWc0OY?usp=drive_link",
      full: "https://drive.google.com/drive/folders/1oq-3k-wP2NEOUZrRoPTJXtxlBwbWc0OY?usp=drive_link",
      eje: 4,
      alt: "Inspección ENKA #8",
   },
   {
      idx: 12,
      name: "WhatsApp Image 2026-07-27 at 2.08.18 PM.jpeg",
      eje: 4,
      ejeClass: "eje-4",
      ejeLabel: "Eje IV: Evaluación de Riesgo Civil",
      thumb: "https://drive.google.com/drive/folders/1oq-3k-wP2NEOUZrRoPTJXtxlBwbWc0OY?usp=drive_link",
      full: "https://drive.google.com/drive/folders/1oq-3k-wP2NEOUZrRoPTJXtxlBwbWc0OY?usp=drive_link",
      alt: "Inspección ENKA #12",
   },
   {
      idx: 16,
      name: "WhatsApp Image 2026-07-28 at 12.16.36 PM.jpeg",
      eje: 4,
      ejeClass: "eje-4",
      ejeLabel: "Eje IV: Evaluación de Riesgo Civil",
      thumb: "https://drive.google.com/drive/folders/1oq-3k-wP2NEOUZrRoPTJXtxlBwbWc0OY?usp=drive_link",
      full: "https://drive.google.com/drive/folders/1oq-3k-wP2NEOUZrRoPTJXtxlBwbWc0OY?usp=drive_link",
      alt: "Inspección ENKA #16",
   },
   {
      idx: 20,
      name: "WhatsApp Image 2026-07-28 at 2.45.32 PM.jpeg",
      eje: 4,
      ejeClass: "eje-4",
      ejeLabel: "Eje IV: Evaluación de Riesgo Civil",
      thumb: "https://drive.google.com/drive/folders/1oq-3k-wP2NEOUZrRoPTJXtxlBwbWc0OY?usp=drive_link",
      full: "https://drive.google.com/drive/folders/1oq-3k-wP2NEOUZrRoPTJXtxlBwbWc0OY?usp=drive_link",
      alt: "Inspección ENKA #20",
   },
   {
      idx: 24,
      name: "WhatsApp Image 2026-07-28 at 5.30.19 PM.jpeg",
      eje: 4,
      ejeClass: "eje-4",
      ejeLabel: "Eje IV: Evaluación de Riesgo Civil",
      thumb: "https://drive.google.com/drive/folders/1oq-3k-wP2NEOUZrRoPTJXtxlBwbWc0OY?usp=drive_link",
      full: "https://drive.google.com/drive/folders/1oq-3k-wP2NEOUZrRoPTJXtxlBwbWc0OY?usp=drive_link",
      alt: "Inspección ENKA #24",
   },
   {
      idx: 28,
      name: "WhatsApp Image 2026-07-28 at 5.30.21 PM.jpeg",
      eje: 4,
      ejeClass: "eje-4",
      ejeLabel: "Eje IV: Evaluación de Riesgo Civil",
      thumb: "https://drive.google.com/drive/folders/1oq-3k-wP2NEOUZrRoPTJXtxlBwbWc0OY?usp=drive_link",
      full: "https://drive.google.com/drive/folders/1oq-3k-wP2NEOUZrRoPTJXtxlBwbWc0OY?usp=drive_link",
      alt: "Inspección ENKA #28",
   },
   {
      idx: 32,
      name: "WhatsApp Image 2026-07-30 at 5.30.30 PM.jpeg",
      eje: 4,
      ejeClass: "eje-4",
      ejeLabel: "Eje IV: Evaluación de Riesgo Civil",
      thumb: "https://drive.google.com/drive/folders/1oq-3k-wP2NEOUZrRoPTJXtxlBwbWc0OY?usp=drive_link",
      full: "https://drive.google.com/drive/folders/1oq-3k-wP2NEOUZrRoPTJXtxlBwbWc0OY?usp=drive_link",
      alt: "Inspección ENKA #32",
   },
   {
      idx: 36,
      name: "WhatsApp Image 2026-07-31 at 9.22.12 AM (1).jpeg",
      eje: 4,
      ejeClass: "eje-4",
      ejeLabel: "Eje IV: Evaluación de Riesgo Civil",
      thumb: "https://drive.google.com/drive/folders/1oq-3k-wP2NEOUZrRoPTJXtxlBwbWc0OY?usp=drive_link",
      full: "https://drive.google.com/drive/folders/1oq-3k-wP2NEOUZrRoPTJXtxlBwbWc0OY?usp=drive_link",
      alt: "Inspección ENKA #36",
   },
   {
      idx: 40,
      name: "WhatsApp Image 2026-08-01 at 1.11.31 PM (1).jpeg",
      eje: 4,
      ejeClass: "eje-4",
      ejeLabel: "Eje IV: Evaluación de Riesgo Civil",
      thumb: "https://drive.google.com/drive/folders/1oq-3k-wP2NEOUZrRoPTJXtxlBwbWc0OY?usp=drive_link",
      full: "https://drive.google.com/drive/folders/1oq-3k-wP2NEOUZrRoPTJXtxlBwbWc0OY?usp=drive_link",
      alt: "Inspección ENKA #40",
   },
   {
      idx: 44,
      name: "WhatsApp Image 2026-08-01 at 1.11.33 PM (1).jpeg",
      eje: 4,
      ejeClass: "eje-4",
      ejeLabel: "Eje IV: Evaluación de Riesgo Civil",
      thumb: "https://drive.google.com/drive/folders/1oq-3k-wP2NEOUZrRoPTJXtxlBwbWc0OY?usp=drive_link",
      full: "https://drive.google.com/drive/folders/1oq-3k-wP2NEOUZrRoPTJXtxlBwbWc0OY?usp=drive_link",
      alt: "Inspección ENKA #44",
   },
   {
      idx: 48,
      name: "WhatsApp Image 2026-08-03 at 11.16.03 AM.jpeg",
      eje: 4,
      ejeClass: "eje-4",
      ejeLabel: "Eje IV: Evaluación de Riesgo Civil",
      thumb: "https://drive.google.com/drive/folders/1oq-3k-wP2NEOUZrRoPTJXtxlBwbWc0OY?usp=drive_link",
      full: "https://drive.google.com/drive/folders/1oq-3k-wP2NEOUZrRoPTJXtxlBwbWc0OY?usp=drive_link",
      alt: "Inspección ENKA #48",
   },
   {
      idx: 52,
      name: "WhatsApp Image 2026-08-03 at 11.21.13 AM.jpeg",
      eje: 4,
      ejeClass: "eje-4",
      ejeLabel: "Eje IV: Evaluación de Riesgo Civil",
      thumb: "https://drive.google.com/drive/folders/1oq-3k-wP2NEOUZrRoPTJXtxlBwbWc0OY?usp=drive_link",
      full: "https://drive.google.com/drive/folders/1oq-3k-wP2NEOUZrRoPTJXtxlBwbWc0OY?usp=drive_link",
      alt: "Inspección ENKA #52",
   },
];

// Helper para obtener clase CSS del eje
export function getEjeClass(eje) {
   return `eje-${eje}`;
}

export function getEjeLabel(eje) {
   const labels = {
      1: "Eje I: Contexto y Fachada",
      2: "Eje II: Autogestión Azotea",
      3: "Eje III: Patologías Estructurales",
      4: "Eje IV: Evaluación de Riesgo Civil",
   };
   return labels[eje] || `Eje ${eje}`;
}
